apiVersion: v1
kind: Service
metadata:
  name: flower-classifier
  labels:
    app: flower-classifier
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9696
    protocol: TCP
    name: http
  selector:
    app: flower-classifier
